### ISSUE TITLE
Consider using AntDesign Blazor as the basic form components.

### ISSUE THREAD

**Issue by ElderJames** [ddjerqq/quickform#1]
Hello @ddjerqq ,

I'm very glad to see this project and it is impressive. And I notice that the library only supports two or there types of controls, I think if using [AntDesign](https://github.com/ant-design-blazor/ant-design-blazor) you can implement more than ten controls including select, number,treeselect,autocomplete,datepicker,rangepicker, and so on.

Best wishes,
James

**Comment by ddjerqq** [comment]
maybe I forgot to include it in the docs, but the library supports date pickers (built into html), selects (only enums right now), data list options (+ custom validation to see if the inputted item is valud), number ranges, number inputs, tims, date + time, only date, URLs, so on. Perhaps you meant something else?

**Comment by ddjerqq** [comment]
you can see some other form controls, such as date pickers, number ranges, and so on [here](https://github.com/ddjerqq/QuickForm/blob/master/samples/IntermediateForm.razor)
